### ISSUE TITLE
Tales of Xillia packing fails

### ISSUE THREAD

**Issue by Sora3100** [AdmiralCurtiss/HyoutaTools#13]
When trying to pack back a TLDAT, the program just fails. Below's the inputted command, and the resulting error:

```
.\HyoutaToolsCLI.exe ToXtldatp "D:\Emulation\rpcs3\dev_hdd0\game\NPUB31136\USRDIR\FILEHEADER.TOFHDB" "D:\Emulation\rpcs3\dev_hdd0\game\NPUB31136\USRDIR\EXTRACT" "D:\Emulation\rpcs3\dev_hdd0\game\NPUB31136\USRDIR\new\TLFILE.TLDAT" "D:\Emulation\rpcs3\dev_hdd0\game\NPUB31136\USRDIR\new\FILEHEADER.TOFHDB"
Directory 'HyoutaToolsPlugins' not found, not loading any plugins.

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at HyoutaUtils.HexUtils.ParseDecOrHex(String s) in D:\Downloads\HyoutaTools\HyoutaUtils\HyoutaUtils\HexUtils.cs:line 25
   at HyoutaTools.Tales.Xillia.TldatPack.Program.Execute(List`1 args) in D:\Downloads\HyoutaTools\Tales\Xillia\TldatPack\Program.cs:line 26
   at HyoutaToolsCLI.Program.Main(String[] args) in D:\Downloads\HyoutaTools\HyoutaToolsCLI\Program.cs:line 18
```

**Comment by AdmiralCurtiss** [comment]
You probably have extra files in your extracted data folder, if I had to guess? The folder should only contain the original files or their replacements. I don't support adding new files into the archive at the moment.

**Comment by AdmiralCurtiss** [comment]
(admittedly this could be better documented and give better error messages)

**Comment by Sora3100** [comment]
That would be it, the program I used to edit files makes backups of the files after saving, after moving them out, it now works as it should. Thanks!

And yeah, better documentation/error messages would be appreciated

**Comment by AdmiralCurtiss** [comment]
I have adjusted this, I hope it's more clear now.
